### ISSUE TITLE
Console commands do not work

### ISSUE THREAD

**Issue by Munnalla** [harold-spgt/InfoHeads#97]
Initially using PAPI OI tried to have the console use economy to give a player a specified amount of money and it wasn't working, so I tried using luckperms papi and that was not working either. 

After a lot of trial and error, research and contacting support on the discord I realized the plugin itself was not working. I tried using the console command to give a player an item, put a player in creative and so on and nothing is working.

**Comment by harold-spgt** [comment]
This will be worked on as part of the 1.20 update

**Comment by harold-spgt** [comment]
Could not replicate, I assume this is a 1.20 issue which has now been updated and supported fully. Otherwise please reopen this issue will steps to reproduce.
